export const SystemRoles = {
	SUPER_ADMIN: 1,
	ADMIN: 2,
	PAYROLL_MANAGER: 3,
	HR: 4,
};

export const monthNames = [
	'January',
	'February',
	'March',
	'April',
	'May',
	'June',
	'July',
	'August',
	'September',
	'October',
	'November',
	'December',
];

// export const DefaultPermissions = [
// 	{ permissionName: 'Basic & Personal Details', sortId: 1 },
// 	{ permissionName: 'Salary Details', sortId: 2 },
// 	{ permissionName: 'Employee Payment Information', sortId: 3 },
// 	{ permissionName: 'Employee Loan', sortId: 4 },
// 	{ permissionName: 'Employee Declarations', sortId: 5 },
// 	{ permissionName: 'Run Payroll', sortId: 6 },
// 	{ permissionName: 'Reimbursements', sortId: 7 },
// 	{ permissionName: 'Proof Of Investments', sortId: 8 },
// 	{ permissionName: 'Salary Revision', sortId: 9 },
// 	{ permissionName: 'Branches', sortId: 10 },
// 	{ permissionName: 'Departments', sortId: 11 },
// 	{ permissionName: 'Job Grade', sortId: 12 },
// 	{ permissionName: 'Payment Type', sortId: 13 },
// 	{ permissionName: 'Payment Method', sortId: 14 },
// 	{ permissionName: 'Pay Point', sortId: 15 },
// 	{ permissionName: 'Earning', sortId: 16 },
// 	{ permissionName: 'Deduction', sortId: 17 },
// 	{ permissionName: 'Payroll Reports', sortId: 18 },
// 	{ permissionName: 'Earning and Deduction Reports', sortId: 19 },
// 	{ permissionName: 'Tax Reports', sortId: 20 },
// ];

export const DefaultAdminPermissions = [
	{
		moduleName: 'Users',
		sortId: 1,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Roles',
		sortId: 2,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Basic & Personal Details',
		sortId: 3,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Salary Details',
		sortId: 4,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Employee Payment Information',
		sortId: 5,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Employee Loan',
		sortId: 6,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Employee Declarations',
		sortId: 7,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Run Payroll',
		sortId: 8,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Reimbursements',
		sortId: 9,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Proof Of Investments',
		sortId: 10,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Salary Revision',
		sortId: 11,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Branches',
		sortId: 12,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Departments',
		sortId: 13,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Job Grade',
		sortId: 14,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Payment Type',
		sortId: 15,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Payment Method',
		sortId: 16,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Pay Point',
		sortId: 17,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Earning',
		sortId: 18,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Deduction',
		sortId: 19,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Payroll Reports',
		sortId: 20,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Earning and Deduction Reports',
		sortId: 21,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
	{
		moduleName: 'Tax Reports',
		sortId: 22,
		all: true,
		view: true,
		edit: true,
		delete: true,
		add: true,
	},
];

export const defaultCompanies = [
	{
		name: 'Acton Beverages Limited',
		code: null,
		tpin: '1002180437',
		address: 'Plot 4130, Off Government Road Chimwemwe Kitwe, Copperbelt',
		email: 'actonbeverages@gmail.com',
	},
	{
		name: 'Acton Holdings Limited',
		code: null,
		tpin: '1001641942',
		address: 'Plot 4150 Off Government Road Chimwemwe Kitwe, Copperbelt, 21125',
		email: 'Sales@actongrp.com',
	},
	{
		name: 'Acton Investments Limited',
		code: null,
		tpin: '1001902451',
		address: 'Plot # 4109. Of Government Road Kitwe, Copperbelt',
		email: 'Sales@actongrp.com',
	},
	{
		name: 'Athol Plastics Limited',
		code: null,
		tpin: '1001635090',
		address: 'Plot 4140, Off Government Road Kitwe, Copperbelt',
		email: 'BHAVIK@ACTONGRP.COM',
	},
	{
		name: 'Chrometec Limited',
		code: null,
		tpin: '1003466208',
		address: 'Plot 4019 Government Road Chimwemwe Kitwe, Copperbelt, 21125',
		email: '',
	},
	{
		name: 'Copperbelt Fasteners Limited',
		code: null,
		tpin: '1001655546',
		address: 'UNIT 7 VIBHAV BUSINESS PARK PLOT NO 2810, CHINGOLA ROAD KITWE',
		email: 'cbfizambia@gmail.com',
	},
	{
		name: 'Damru Enterprises Limited',
		code: null,
		tpin: '1001687311',
		address:
			'Vibhav Business Park, Phase 4 Plot No 2810, Chingola Road Kitwe, Copperbelt',
		email: 'damrukitwe@gmail.com',
	},
	{
		name: 'Northwood Environmental Limited',
		code: null,
		tpin: '1003196379',
		address: 'Plot 4109 Government Road Chimwemwe Kitwe, Copperbelt, 21125',
		email: '',
	},
	{
		name: 'Precise Corporate Solutions Ltd',
		code: null,
		tpin: '1002224132',
		address: 'Plot 4130 Government Road Chimwemwe Kitwe, Copperbelt, 21125',
		email: '',
	},
	{
		name: 'Vibhav Logistics Limited',
		code: null,
		tpin: '2178369288',
		address: 'Plot 4130 Government Road Chimwemwe Kitwe, Copperbelt, 21125',
		email: '',
	},
	{
		name: 'Vibhav Quarries & Constructions Limited',
		code: null,
		tpin: '1001848200',
		address: 'Plot 4130 Government Road Chimwemwe Kitwe, Copperbelt, 21125',
		email: '',
	},
];

export const DefaultPermissions = [
	{
		moduleName: 'Users',
		sortId: 1,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Roles',
		sortId: 2,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Basic & Personal Details',
		sortId: 3,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Salary Details',
		sortId: 4,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Employee Payment Information',
		sortId: 5,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Employee Loan',
		sortId: 6,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Employee Declarations',
		sortId: 7,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Run Payroll',
		sortId: 8,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Reimbursements',
		sortId: 9,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Proof Of Investments',
		sortId: 10,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Salary Revision',
		sortId: 11,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Branches',
		sortId: 12,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Departments',
		sortId: 13,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Job Grade',
		sortId: 14,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Payment Type',
		sortId: 15,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Payment Method',
		sortId: 16,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Pay Point',
		sortId: 17,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Earning',
		sortId: 18,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Deduction',
		sortId: 19,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Payroll Reports',
		sortId: 20,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Earning and Deduction Reports',
		sortId: 21,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
	{
		moduleName: 'Tax Reports',
		sortId: 22,
		all: false,
		view: false,
		edit: false,
		delete: false,
		add: false,
	},
];
